### PR TITLE
Update build badges in README

### PR DESCRIPTION
**Pull request by mzgoddard**

### CODE REVIEW

**Comment by kadamwhite** [comment]
Not obvious what this is doing?

**Comment by mzgoddard** [comment]
The badges were configured for the point in time they were private projects (travis) or configured on a different ci account (appveyor). This updates the badges for public testing on travis, .com -> .org, and changes the appveyor badge to a different account.

Thanks for looking at this @kadamwhite.

**Comment by mzgoddard** [comment]
This doesn't solve an annoying problem yes where appveyor doesn't report status to PRs.

**Comment by mzgoddard** [comment]
https://ci.appveyor.com/project/robocoup/boxart-boiler/build/5

**Pull request merged**
